### ISSUE TITLE
Revised Assignment 1 Dataset 

### ISSUE THREAD

**Issue by jcmeinhardt** [SES-5215-F2020/jmeinhardt-quant#2]
Revised dataset for review.

HTML: https://ses-5215-f2020.github.io/jmeinhardt-quant/County_Level_Dataframe

**Comment by saratepfer** [comment]
**Comments on code**
Your table showing the assembled dataframe seems to be cut off. (It doesn't show all 12 variables.) I believe you can use the following code: head(df, n = 10), where df is the name of your dataframe to display everything. Otherwise, good job wrangling the data. If you're interested, there may be a more efficient way to assign the region and county to each observation that avoids duplicating the same code for the different counties/regions.
