### ISSUE TITLE
Assignment 2 Draft: In Need of Review (not grading) due to error code

### ISSUE THREAD

**Issue by jcmeinhardt** [SES-5215-F2020/jmeinhardt-quant#3]
Hi Carole,

Thanks for looking over this! The file is Assignment2_Quant_Draft. 

I'm running into an error code as I try to knit my file for assignment 2 that I'm hoping someone can advise me about. It reads:

 

"Quitting from lines 96-99 (Final_Assignment2_Quant.Rmd) Error in png(..., res = dpi, units = "in") : invalid 'filename' Calls: <Anonymous> ... in_dir -> plot2dev -> do.call -> <Anonymous> -> png"

 

The code chunk it is referring to is:

```{r histogram population below 100% poverty Jefferson}
hist<- ggplot(Jefferson_tract_data, aes(x = poverty_100E)) +
geom_histogram() 
hist
```

This isn't the first histogram in the dataset, nor the first time I use the that file name in the code, so I'm sure what I'm missing here. 

And one more question: two of my categorical variables for this dataset are county and region. It wouldn't make sense for me to run t-tests on these categorical variables correct? As that would be estimating what percentage of tracts or counties make up the dataset, when we already know the true proportion? I'm a little confused on this point. 

Thank you again!

Julia

**Comment by c-voulgaris** [comment]
Okay - I figured it out, and I guess - congratulations!

You've discovered a rule in rmarkdown I wasn't aware of. Apparently, you can't have a % sign in the name of your code chunk.

So in the line at the beginning of a code chunk that looks like this:

{r histogram population between 100-149% poverty Jefferson}

Get rid of the % sign (you could just replace it with 'pct'?) It happens in three or four places in your code, and it only makes a difference if trying to create a figure from that code chunk.

I think what's happening is, when R is knitting, it creates the figure to go in the html file by creating a (hidden) png file with image so that it can embed that image into the html file. The filename for that file is based on the name of your code chunk, and it can't have a % sign in the filename.

I would think of this as a bug in the knitting function, but the workaround is just to not use % signs in the names of your code chunks.

Weird issue, but I'm glad to have figured it out.
