### ISSUE TITLE
Assignment 3 Ready for Grading (relationships)

### ISSUE THREAD

**Issue by jcmeinhardt** [SES-5215-F2020/jmeinhardt-quant#5]
Hi Carole or Sara,

Here's the html for Assignment 3: https://ses-5215-f2020.github.io/jmeinhardt-quant/Assignment_3_QUANT

This document is admittedly huge because I made the mistake of not taking Sara's advice early on and converting some continuous variables into categorical! I ended up being in sort of deep and so plunged forward instead of going back, but I think I should and will go back and do some mutations and add some more relevant variables/remove irrelevant ones if we're compiling this for a final report. 

I nevertheless learned a TON from this process which I think will really help as I'm compiling datasets in the future. I tried to organize with tabs so it's easier for you to navigate. 

All the best,

Julia

**Comment by saratepfer** [comment]
Whew! You did a really nice job presenting a lot of information in this assignment. I'm glad to hear that you are going back and refining your variables so that you aren't working with so many. Overall, I think this looks good, and I don't have any big comments on your code or on the content. I'm happy to review your revised version, once you have your new variables, if you'd like.
